### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by norato** [Objectway/json-rest-server#2]
![image](https://cloud.githubusercontent.com/assets/395588/23313964/924241e0-fa9e-11e6-8923-6905ebb66708.png)

![image](https://cloud.githubusercontent.com/assets/395588/23313823/0b2032da-fa9e-11e6-866d-3e74298557bb.png)

**Comment by micheledisalvatore** [comment]
Hi @norato please can you post your json files to replicate it on my local? thanks :)

**Comment by norato** [comment]
@micheledisalvatore i didn't work for any json file here. I removed this package and reinstalled, but the error continued. Tnx for your attention! :-)

**Comment by sergioedo** [comment]
I've found in the same situtation... this PR fixes it for me.
